name: 'eval_pipeline'
version: '0.1.0'
config-version: 2
profile: 'eval_pipeline'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  eval_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  eval_pipeline:
    +quote_columns: false
